- name: Remove motd messages.
  file:
    path: '/etc/update-motd.d/{{ item }}'
    state: absent
  loop:
    - 50-landscape-sysinfo
    - 80-esm
    - 90-updates-available
    - 95-hwe-eol
    - 98-fsck-at-reboot
    - 10-help-text
    - 50-motd-news
    - 80-livepatch
    - 91-release-upgrade
    - 97-overlayroot
    - 98-reboot-required
- name: "Installing motd on {{ motdname }}" 
  copy:
    src: "{{ motdname }}.txt"
    dest: "/etc/update-motd.d/99-{{ motdname }}"
    owner: root
    group: root
    mode: '0755'
