---
- hosts: all
  tasks:
    - name: Set the hostname 
      hostname:
        name: tux

    # Firewall 
    - name: Allowing IP forwarding in UFW 
      lineinfile:
        path: /etc/default/ufw 
        regexp: '^DEFAULT_FORWARD_POLICY='
        line: 'DEFAULT_FORWARD_POLICY="ACCEPT"'        
    - name: Enable IP fowarding in the kernel 
      sysctl:
        name: net.ipv4.ip_forward
        value: 1 
        reload: yes
    - name: Add masquerade for the internal network. 
      blockinfile:
        path: /etc/ufw/before.rules
        marker: "## {mark} ANSIBLE: provide NAT for the vm network. ##"
        block: |
          *nat
          :PREROUTING ACCEPT [0:0]
          -A POSTROUTING -s 192.168.100.0/24 -o br0 -j MASQUERADE
          COMMIT
    - name: Reset the firewall 
      ufw:
        state: reset
    - name: Enable the firewall 
      ufw:
        state: enabled
        policy: deny
    - name: Allow SSH connections 
      ufw:
        rule: allow
        name: OpenSSH


    # Packages 
    - name: Set package update policy.
      apt:
        update_cache: yes
        cache_valid_time: 86400
    - name: Add Docker key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker repo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present
    - name: Install packages
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli 
          - containerd.io
          - tree 

    # Enable LXD 
    - name: Configure LXD
      command: /usr/bin/lxd init --auto 

    # Add me
    - name: Setup my account.
      user:
        name: mmatera
        comment: Mike Matera
        password: $6$to1tkyvYy4KX/4hA$TrJ.uAGCjVrcN6Td/P4ozjsn3fTCe6S8gFLBOCArbX2ruUulszWHlUigC3/BcldU781PmYcStbjpF.h6p/vuN/
        groups: 
          - admin
          - docker
          - lxd
        shell: /bin/bash
        append: yes
    - name: Add my keys 
      authorized_key:
        user: mmatera
        state: present
        key: '{{ item }}'
      with_file:
        - public_keys/opus.pub
        - public_keys/mouthfeel.pub
        - public_keys/phoenix.pub
        - public_keys/turbine.pub

