#! /usr/bin/env python3 

import pwd
import subprocess
from pathlib import Path 

def main():
    cis90 = Path('/home/cis90')
    scripts = list(cis90.glob('*/bin/myscript'))
    scripts.sort()

    runme = 0
    while runme != 99:
        subprocess.run('clear')
        print("""
  *********************************************************
  *                CIS 90 Online Projects                 *
  *********************************************************
    """)


        for index, script in enumerate(scripts):
            user = script.owner()
            pwuser = pwd.getpwnam(user)
            print(f"  {index+1}) {pwuser[4]} ({user})")
        print(f"\n  99) quit\n")

        try:
            runme = int(input('Enter Your Choice: '))
        except:
            continue

        if runme < 1 or runme > len(scripts):
            continue

        subprocess.run(str(scripts[runme-1]), shell=True)
        input('\n\nHit the Enter key to return to the main menu.')

if __name__ == '__main__':
    main()
