
homeSize: 8Gi
homeStorageClassName: ssd-ha

customizeRepo: "https://github.com/mike-matera/cloud-linux.git" 
customizeRepoCommand: "cd playbooks && ./base.sh"
privileged: false

service:
  type: LoadBalancer
  loadBalancerIP: 172.30.5.242
  annotations:
    metallb.universe.tf/allow-shared-ip: share-me-arya

resources: 
  requests:
    cpu: 2000m
    memory: 16Gi
  limits:
    cpu: 4000m
    memory: 32Gi

ssh:
  sshd_config: |
    Include /etc/ssh/sshd_config.d/*.conf
    PasswordAuthentication no
    KbdInteractiveAuthentication no
    UsePAM yes
    X11Forwarding yes
    PrintMotd no
    AcceptEnv LANG LC_*
    Subsystem	sftp	/usr/lib/openssh/sftp-server
    TrustedUserCAKeys /etc/ssh/ca/ca_key.pub
    HostCertificate /etc/ssh/ssh_host_rsa_key-cert.pub
    ClientAliveInterval 10
    ClientAliveCountMax 10
