---
- hosts: opus.cis.cabrillo.edu
  become: true
  tasks:
    - name: Installing motd on opus
      copy:
        src: motd/opus.txt
        dest: /etc/update-motd.d/99-opus
        owner: root
        group: root
        mode: '0755'

    - name: Add the cis90 group.
      group:
        name: cis90
        state: present

    - name: Add the cis191 group.
      group:
        name: cis191
        state: present

    - name: Add the cis192 group.
      group:
        name: cis192
        state: present

    - name: Install cis90 packages on opus
      apt:
        pkg:
          - tree
          - zsh
          - csh
          - tcsh
          - python3-pip
          - sysvbanner
          - emacs
          - spell 

    - name: Upload the skeleton files. 
      file:
        path: /etc/student-skel
        state: directory
        mode: '0755'

    - name: Create the student skel directory. 
      unarchive:
        src: skel/student-skel.tar
        dest: /etc/student-skel

- hosts: opus.cis.cabrillo.edu
  become: true
  tasks:
    - include_vars: dogs.yaml
    - name: Add dog accounts.
      user:
        name: "{{ item.name }}"
        comment: "{{ item.comment }}"
        password: "{{ item.password }}"
        groups: "{{ item.groups }}"
        home: "{{ item.home }}"
        skeleton: /etc/student-skel
        shell: /bin/bash
        append: yes
      loop: "{{ dogs | flatten(levels=1) }}"

- hosts: opus.cis.cabrillo.edu
  tags: postfix
  become: true
  name: Install postfix on opus
  tasks:
    - name: Configure postfix mailer type
      debconf:
        name: main_mailer_type
        question: postfix/main_mailer_type
        vtype: select
        value: Internet Site
    - name: Configure postfix root address
      debconf:
        name: root_address
        question: postfix/root_address
        vtype: string
        value: mmatera
    - name: Configure postfix listening protocols
      debconf:
        name: protocols
        question: postfix/protocols
        vtype: select
        value: all
    - name: Configure postfix mailname
      debconf:
        name: mailname
        question: postfix/mailname
        vtype: string
        value: opus.cis.cabrillo.edu
    - name: Configure postfix mailbox limit
      debconf:
        name: mailbox_limit
        question: postfix/mailbox_limit
        vtype: string
        value: 0
    - name: Configure postfix networks
      debconf:
        name: mynetworks
        question: postfix/mynetworks
        vtype: string
        value: 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
    - name: Install mail server and related packages
      apt:
        pkg:
          - alpine 
          - postfix 
          - mailutils

