---
- hosts: all
  tasks:

    # Update /etc/hosts 
    - name: Configure /etc/hosts 
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      loop:
        - 192.168.100.1  tux tux.cis.cabrillo.edu
        - 192.168.100.10 defiant defiant.cis.cabrillo.edu
        - 192.168.100.11 intrepid intrepid.cis.cabrillo.edu
        - 192.168.100.12 enterprise enterprise.cis.cabrillo.edu 
        - 192.168.100.13 freedom freedom.cis.cabrillo.edu
        - 192.168.100.14 excalibur excalibur.cis.cabrillo.edu
        - 192.168.100.15 lexington lexington.cis.cabrillo.edu 
        
    - name: Fix opus3 in /etc/hosts.  
      lineinfile:
        path: /etc/hosts
        regexp: 'opus3'
        line: 172.19.100.2   opus3 opus3.cis.cabrillo.edu

    - name: Add the cis90 group.
      group:
        name: cis90
        state: present

    - name: Add the cis191 group.
      group:
        name: cis191
        state: present

    # Add me
    - name: Update my account.
      user:
        name: mmatera
        comment: Mike Matera
        password: $6$to1tkyvYy4KX/4hA$TrJ.uAGCjVrcN6Td/P4ozjsn3fTCe6S8gFLBOCArbX2ruUulszWHlUigC3/BcldU781PmYcStbjpF.h6p/vuN/
        shell: /bin/bash
    - name: Add my keys 
      authorized_key:
        user: mmatera
        state: present
        key: '{{ item }}'
      with_file:
        - public_keys/opus.pub
        - public_keys/opus3.pub
        - public_keys/mouthfeel.pub
        - public_keys/phoenix.pub
        - public_keys/tux.pub
        - public_keys/turbine.pub

- hosts: ubuntu
  tasks:
    - name: Install base packages on Ubuntu
      apt:
        pkg:
          - tree
          - zsh
          - python3-pip
          - sysvbanner

- hosts: debian
  tasks:
    - name: Install base packages on Debian
      apt:
        pkg:
          - vim
          - tree
          - sysvbanner

- hosts: fedora
  tasks:
    - name: Install base packages on Fedora
      dnf:
        name: 
        - vim
        - banner

- hosts: opensuse
  tasks:
    - name: Install base packages on OpenSuse 
      zypper:
        name: 
          - tree

- hosts: login-servers
  tasks:
    - include_vars: dogs.yaml
    # Create the user skeleton
    - name: Upload the skeleton files. 
      file:
        path: /etc/student-skel
        state: directory
        mode: '0755'
    - name: Create the student skel directory. 
      unarchive:
        src: student-skel.tar
        dest: /etc/student-skel
    - name: Add dog accounts.
      user:
        name: "{{ item.name }}"
        comment: "{{ item.comment }}"
        password: "{{ item.password }}"
        groups: "{{ item.groups }}"
        home: "{{ item.home }}"
        skeleton: /etc/student-skel
        shell: /bin/bash
        append: yes
      loop: "{{ dogs | flatten(levels=1) }}"

- hosts: all
  tasks:
    - include_vars: dogs.yaml
    - name: Add dog accounts.
      user:
        name: "{{ item.name }}"
        comment: "{{ item.comment }}"
        password: "{{ item.password }}"
        groups: "{{ item.groups }}"
        home: "{{ item.home }}"
        shell: /bin/bash
        append: yes
      loop: "{{ dogs | flatten(levels=1) }}"
    - name: Add opus3 key to dog accounts.
      authorized_key:
        user: "{{ item.name }}"
        state: present
        key: "{{ lookup('file', 'public_keys/opus3.pub') }}"
      loop: "{{ dogs | flatten(levels=1) }}"

# Add motd files. 
- hosts: opus3.cis.cabrillo.edu
  tasks:
    - name: Setting the hostname on opus3
      hostname:
        name: opus3.cis.cabrillo.edu
    - name: Installing motd on opus
      copy:
        src: motd/opus.txt
        dest: /etc/update-motd.d/99-opus
        owner: root
        group: root
        mode: '0755'

- hosts: defiant.cis.cabrillo.edu
  tasks:
    - name: Installing motd on defiant
      copy:
        src: motd/defiant.txt
        dest: /etc/update-motd.d/99-defiant
        owner: root
        group: root
        mode: '0755'
    - name: Add sisko account.
      user:
        name: sisko
        comment: Benjamin Sisko
        password: !
    - name: Add opus3 key to sisko account.
      authorized_key:
        user: sisko
        state: present
        key: "{{ lookup('file', 'public_keys/opus3.pub') }}"

- hosts: intrepid.cis.cabrillo.edu
  tasks:
    - name: Installing motd on intrepid
      copy:
        src: motd/intrepid.txt
        dest: /etc/update-motd.d/99-intrepid
        owner: root
        group: root
        mode: '0755'
    - name: Add commodore Stone
      user:
        name: cstone
        comment: Commodore Stone
        password: !
    - name: Add opus3 key to cstone account.
      authorized_key:
        user: cstone
        state: present
        key: "{{ lookup('file', 'public_keys/opus3.pub') }}"
    - name: Add spock
      user:
        name: spock
        comment: Spock
        password: !
    - name: Add opus3 key to spock account.
      authorized_key:
        user: spock
        state: present
        key: "{{ lookup('file', 'public_keys/opus3.pub') }}"

- hosts: enterprise.cis.cabrillo.edu
  tasks:
    - name: Installing motd on enterprise
      copy:
        src: motd/enterprise.txt
        dest: /etc/motd
        owner: root
        group: root
        mode: '0644'
    - name: Add captiain Kirk
      user:
        name: kirk
        comment: James T. Kirk
        password: !
    - name: Add opus3 key to kirk account.
      authorized_key:
        user: kirk
        state: present
        key: "{{ lookup('file', 'public_keys/opus3.pub') }}"
    - name: Add spock
      user:
        name: spock
        comment: Spock
        password: !
    - name: Add opus3 key to spock account.
      authorized_key:
        user: spock
        state: present
        key: "{{ lookup('file', 'public_keys/opus3.pub') }}"
    - name: Add sulu
      user:
        name: sulu
        comment: Hikaru Sulu
        password: !
    - name: Add opus3 key to sulu account.
      authorized_key:
        user: sulu
        state: present
        key: "{{ lookup('file', 'public_keys/opus3.pub') }}"

- hosts: freedom.cis.cabrillo.edu
  tasks:
    - name: Installing motd on freedom
      copy:
        src: motd/freedom.txt
        dest: /etc/motd
        owner: root
        group: root
        mode: '0644'

- hosts: excalibur.cis.cabrillo.edu
  tasks:
    - name: Installing motd on excalibur
      copy:
        src: motd/excalibur.txt
        dest: /etc/motd
        owner: root
        group: root
        mode: '0644'

- hosts: lexington.cis.cabrillo.edu
  tasks:
    - name: Installing motd on lexington 
      copy:
        src: motd/lexington.txt
        dest: /etc/motd
        owner: root
        group: root
        mode: '0644'
    - name: Add dax
      user:
        name: dax
        comment: Jadzea Dax
        password: !
    - name: Add opus3 key to dax account.
      authorized_key:
        user: dax
        state: present
        key: "{{ lookup('file', 'public_keys/opus3.pub') }}"

- hosts: opus3.cis.cabrillo.edu
  tags: postfix
  name: Install postfix on opus3 
  tasks:
    - name: Configure postfix mailer type
      debconf:
        name: main_mailer_type
        question: postfix/main_mailer_type
        vtype: select
        value: Internet Site
    - name: Configure postfix root address
      debconf:
        name: root_address
        question: postfix/root_address
        vtype: string
        value: mmatera
    - name: Configure postfix listening protocols
      debconf:
        name: protocols
        question: postfix/protocols
        vtype: select
        value: all
    - name: Configure postfix mailname
      debconf:
        name: mailname
        question: postfix/mailname
        vtype: string
        value: opus3.cis.cabrillo.edu
    - name: Configure postfix mailbox limit
      debconf:
        name: mailbox_limit
        question: postfix/mailbox_limit
        vtype: string
        value: 0
    - name: Configure postfix networks
      debconf:
        name: mynetworks
        question: postfix/mynetworks
        vtype: string
        value: 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
    - name: Install extra packages on opus3
      apt:
        pkg:
          - alpine 
          - postfix 
