
- name: Configure /etc/hosts 
  lineinfile:
    path: /etc/hosts
    regexp: '^(?!127).*\s{{ item.host | regex_escape() }}\s.*'
    line: "{{ item.ipv4 }} {{ item.host }} {{ item.host }}.cis.cabrillo.edu"
  loop:
    - { host: 'tux', ipv4: '172.19.100.1' } 
    - { host: 'opus3', ipv4: '172.19.100.2' } 
    - { host: 'jupyter', ipv4: '172.19.100.3' } 
    - { host: 'defiant', ipv4: '192.168.100.10' } 
    - { host: 'intrepid', ipv4: '192.168.100.11' } 
    - { host: 'enterprise', ipv4: '192.168.100.12' }
    - { host: 'freedom', ipv4: '192.168.100.13' } 
    - { host: 'excalibur', ipv4: '192.168.100.14' }
    - { host: 'lexington', ipv4: '192.168.100.15' } 
    - { host: 'sun-hwa-v', ipv4: '192.168.100.20' } 
    - { host: 'sun-hwa-vii', ipv4: '192.168.100.21' }

- name: Make user for mmatera
  user:
    name: mmatera
    comment: Mike Matera
    password: $6$to1tkyvYy4KX/4hA$TrJ.uAGCjVrcN6Td/P4ozjsn3fTCe6S8gFLBOCArbX2ruUulszWHlUigC3/BcldU781PmYcStbjpF.h6p/vuN/
    shell: /bin/bash
- name: Add my keys 
  authorized_key:
    user: mmatera
    state: present
    key: '{{ item }}'
  with_file:
    - files/opus.pub
    - files/mouthfeel.pub
    - files/phoenix.pub
    - files/tux.pub
    - files/turbine.pub
