# -*- mode: ruby -*-
# vi: set ft=ruby :

# This Vagrantfile is for testing the jupyter playbook. 

require 'pathname'

# Look for an anisble playbook in this file to setup the VM. 
# It's okay if the file doesn't exist. 
playbook = 'jupyter.yaml'

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 443, host: 8443, host_ip: "127.0.0.1"

  # Check to see if the playbook is available. 
  if File.exist?(playbook)
    # Run Ansible from the Vagrant VM
    config.vm.provision "ansible_local" do |ansible|
      ansible.playbook = playbook
    end
  end

end
