- hosts: all
  become: true
  tasks:
    - name: Creating motd
      lineinfile:
        create: yes
        path: /etc/update-motd.d/99-opus
        owner: root
        group: root
        mode: '0755'
        line: "#! /bin/bash" 

    - name: Customizing motd
      blockinfile:
        path: /etc/update-motd.d/99-opus
        owner: root
        group: root
        mode: '0755'
        block: |
          cat <<EOF
              _
            ('v')    
           \/-=-\/
           (\_=_/)
            ~~ ~~  

          Welcome to your own private Opus
          Serving YOU!

          EOF
          
    - name: Install cis90 packages
      apt:
        pkg:
          - tree
          - zsh
          - python3-pip
          - sysvbanner
          - emacs
          - spell 

    - name: Upload the skeleton files. 
      file:
        path: /etc/student-skel
        state: directory
        mode: '0755'

    - name: Create the student skel directory. 
      unarchive:
        src: http://www.lifealgorithmic.com/_static/cis-90/student-skel.tar 
        dest: /etc/student-skel
        remote_src: yes 
        
    - name: Add the cis90 group.
      group:
        name: cis90
        state: present

    - name: Add the Benji account
      user:
        name: simben90
        comment: Benji Simms
        groups: users, cis90
        home: /home/cis90/simben90
        skeleton: /etc/student-skel
        shell: /bin/bash
        append: yes
