# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'pathname'

# Change this if you want to add or remove extra disks. 
num_disks = 0

# Look for an anisble playbook in this file to setup the VM. 
# It's okay if the file doesn't exist. 
playbook = 'playbook.yaml'

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    for i in 0..num_disks-1
      disk = 'extra' + i.to_s + '.vdi'
      unless File.exist?(disk)
        vb.customize ['createmedium', '--filename', disk, '--variant', 'Fixed', '--size', 1024]
      end
      vb.customize ['storageattach', :id,  '--storagectl', 'SCSI', '--port', 2 + i, '--device', 0, '--type', 'hdd', '--medium', disk]
    end

    vb.memory = "1024"
  end

  # Check to see if the playbook is available. 
  if File.exist?(playbook)
    # Run Ansible from the Vagrant VM
    config.vm.provision "ansible_local" do |ansible|
      ansible.playbook = playbook
    end
  end

end
