#!/bin/bash
# Trouble L5
event=L5

# Clean up old trouble
/root/trouble-none

# Make new trouble
cp /etc/.trouble/profile.d/z-cis90-$event.sh /etc/profile.d/
chmod 755 /etc/.trouble/bin/$event
echo 'Congratulations path builder!' > /etc/mensaje
exit
