#!/bin/bash
# Trouble T2
event=T2

# Clean up old trouble
/root/trouble-none

# Make new trouble
cp /etc/.trouble/profile.d/z-cis90-$event.sh /etc/profile.d/
chmod 755 /etc/.trouble/bin/$event

echo Trouble made for $event
sleep 1

exit
