---
- hosts: all
  tasks:

    # Add me
    - name: Update mmatera account.
      user:
        name: mmatera
        comment: Mike Matera
        password: $6$to1tkyvYy4KX/4hA$TrJ.uAGCjVrcN6Td/P4ozjsn3fTCe6S8gFLBOCArbX2ruUulszWHlUigC3/BcldU781PmYcStbjpF.h6p/vuN/
        shell: /bin/bash
        append: yes
    - name: Add my keys 
      authorized_key:
        user: mmatera
        state: present
        key: '{{ item }}'
      with_file:
        - public_keys/opus.pub
        - public_keys/mouthfeel.pub
        - public_keys/phoenix.pub
        - public_keys/tux.pub

    # Install the scavenge program.
    - name: Create the scavenge program. 
      copy:
        src: scavenge/scavenge
        dest: /usr/local/bin/scavenge
        owner: root
        group: root 
        mode: '0755'
    - name: Make the scavenge link 
      file:
        src: /usr/local/bin/scavenge
        dest: /usr/local/bin/sc 
        owner: root
        group: root 
        state: link 
    - name: Copy the scavenge infrastructure 
      copy:
        src: scavenge/etc/scavenge
        dest: /etc 
        owner: root
        group: root 

        