- name: "Install {{ source | basename }} "
  ansible.builtin.copy:
    src: "{{ source }}"
    dest: "/tmp/{{ source | basename }}" 
    mode: '0600'
    owner: root
    group: root 
- name: "Armor /tmp/{{ source | basename }}"
  ansible.builtin.shell: PATH=${PATH}:/usr/local/bin pyscramble "/tmp/{{ source | basename }}"
  args:
    chdir: /tmp
- name: "Remove /tmp/{{ source | basename }}"
  ansible.builtin.file:
    path: "/tmp/{{ source | basename }}"
    state: absent
- name: "Install {{ dest }}"
  ansible.builtin.copy:
    src: "/tmp/{{ source | basename | splitext | first }}"
    dest: "{{ dest }}"
    mode: '0755'
    owner: root
    group: root 
    remote_src: yes
- name: "Cleanup /tmp/{{ source | basename | splitext | first }}"
  ansible.builtin.file:
    path: "/tmp/{{ source | basename | splitext | first }}"
    state: absent
