--- 
# Setup CIS-90   
- hosts: all
  name: Add cis-90 group.
  remote_user: root 
  tags: 
    - cis90
  tasks:
    - name: Add the cis90 group.
      group:
        name: cis90
        state: present

- hosts: ubuntu
  name: Install packages on Ubuntu hosts.
  remote_user: root 
  tags: 
    - cis90
  tasks:
    - name: Install base packages on Ubuntu
      apt:
        pkg:
          - tree
          - zsh
          - python3-pip
          - sysvbanner
          - emacs
          - spell 

- hosts: debian
  name: Install packages on Debian hosts.
  remote_user: root 
  tags: 
    - cis90
  tasks:
    - name: Install base packages on Debian
      apt:
        pkg:
          - vim
          - tree
          - sysvbanner

- hosts: fedora
  name: Install packages on Fedora hosts.
  remote_user: root 
  tags: 
    - cis90
  tasks:
    - name: Install base packages on Fedora
      dnf:
        name: 
        - vim
        - banner

- hosts: opensuse
  name: Install packages on OpenSUSE hosts.
  remote_user: root 
  tags: 
    - cis90
  tasks:
    - name: Install base packages on OpenSuse 
      zypper:
        name: 
          - tree

# Add motd files. 
- hosts: opus3.cis.cabrillo.edu
  name: Customize opus3
  remote_user: root 
  tags: 
    - cis90
  tasks:
    - name: Setting the hostname on opus3
      hostname:
        name: opus3.cis.cabrillo.edu
    - name: Installing motd on opus
      copy:
        src: cis90/motd/opus.txt
        dest: /etc/update-motd.d/99-opus
        owner: root
        group: root
        mode: '0755'
    - name: Configure postfix mailer type
      debconf:
        name: main_mailer_type
        question: postfix/main_mailer_type
        vtype: select
        value: Internet Site
    - name: Configure postfix root address
      debconf:
        name: root_address
        question: postfix/root_address
        vtype: string
        value: mmatera
    - name: Configure postfix listening protocols
      debconf:
        name: protocols
        question: postfix/protocols
        vtype: select
        value: all
    - name: Configure postfix mailname
      debconf:
        name: mailname
        question: postfix/mailname
        vtype: string
        value: opus3.cis.cabrillo.edu
    - name: Configure postfix mailbox limit
      debconf:
        name: mailbox_limit
        question: postfix/mailbox_limit
        vtype: string
        value: 0
    - name: Configure postfix networks
      debconf:
        name: mynetworks
        question: postfix/mynetworks
        vtype: string
        value: 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
    - name: Install mail server and related packages
      apt:
        pkg:
          - alpine 
          - postfix 
          - mailutils

- hosts: defiant.cis.cabrillo.edu
  name: Customize defiant
  remote_user: root 
  tags: 
    - cis90
  tasks:
    - name: Installing motd on defiant
      copy:
        src: cis90/motd/defiant.txt
        dest: /etc/update-motd.d/99-defiant
        owner: root
        group: root
        mode: '0755'
    - name: Add sisko account.
      user:
        name: sisko
        comment: Benjamin Sisko
        password: !
    - name: Add opus3 key to sisko account.
      authorized_key:
        user: sisko
        state: present
        key: "{{ lookup('file', 'roles/common/files/opus3.pub') }}"

- hosts: intrepid.cis.cabrillo.edu
  name: Customize intrepid
  remote_user: root 
  tags: 
    - cis90
  tasks:
    - name: Installing motd on intrepid
      copy:
        src: cis90/motd/intrepid.txt
        dest: /etc/update-motd.d/99-intrepid
        owner: root
        group: root
        mode: '0755'
    - name: Add commodore Stone
      user:
        name: cstone
        comment: Commodore Stone
        password: !
    - name: Add opus3 key to cstone account.
      authorized_key:
        user: cstone
        state: present
        key: "{{ lookup('file', 'roles/common/files/opus3.pub') }}"
    - name: Add spock
      user:
        name: spock
        comment: Spock
        password: !
    - name: Add opus3 key to spock account.
      authorized_key:
        user: spock
        state: present
        key: "{{ lookup('file', 'roles/common/files/opus3.pub') }}"

- hosts: enterprise.cis.cabrillo.edu
  name: Customize enterprise
  remote_user: root 
  tags: 
    - cis90
  tasks:
    - name: Installing motd on enterprise
      copy:
        src: cis90/motd/enterprise.txt
        dest: /etc/motd
        owner: root
        group: root
        mode: '0644'
    - name: Add captiain Kirk
      user:
        name: kirk
        comment: James T. Kirk
        password: !
    - name: Add opus3 key to kirk account.
      authorized_key:
        user: kirk
        state: present
        key: "{{ lookup('file', 'roles/common/files/opus3.pub') }}"
    - name: Add spock
      user:
        name: spock
        comment: Spock
        password: !
    - name: Add opus3 key to spock account.
      authorized_key:
        user: spock
        state: present
        key: "{{ lookup('file', 'roles/common/files/opus3.pub') }}"
    - name: Add sulu
      user:
        name: sulu
        comment: Hikaru Sulu
        password: !
    - name: Add opus3 key to sulu account.
      authorized_key:
        user: sulu
        state: present
        key: "{{ lookup('file', 'roles/common/files/opus3.pub') }}"

- hosts: freedom.cis.cabrillo.edu
  name: Customize freedom
  remote_user: root 
  tags: 
    - cis90
  tasks:
    - name: Installing motd on freedom
      copy:
        src: cis90/motd/freedom.txt
        dest: /etc/motd
        owner: root
        group: root
        mode: '0644'

- hosts: excalibur.cis.cabrillo.edu
  name: Customize excalibur
  remote_user: root 
  tags: 
    - cis90
  tasks:
    - name: Installing motd on excalibur
      copy:
        src: cis90/motd/excalibur.txt
        dest: /etc/motd
        owner: root
        group: root
        mode: '0644'

- hosts: lexington.cis.cabrillo.edu
  name: Customize lexington
  remote_user: root 
  tags: 
    - cis90
  tasks:
    - name: Installing motd on lexington 
      copy:
        src: cis90/motd/lexington.txt
        dest: /etc/motd
        owner: root
        group: root
        mode: '0644'
    - name: Add dax
      user:
        name: dax
        comment: Jadzea Dax
        password: !
    - name: Add opus3 key to dax account.
      authorized_key:
        user: dax
        state: present
        key: "{{ lookup('file', 'roles/common/files/opus3.pub') }}"

- hosts: sun-hwa-v.cis.cabrillo.edu
  name: Customize sun-hwa-v
  remote_user: root 
  tags: 
    - cis90
  tasks:
    - name: Setting the hostname 
      hostname: 
        name: sun-hwa-v.cis.cabrillo.edu       
    - name: Installing motd on sun-hwa-v
      copy:
        src: cis90/motd/sun-hwa-v.txt
        dest: /etc/motd
        owner: root
        group: root
        mode: '0644'
    - name: Upload the skeleton files. 
      file:
        path: /etc/student-skel
        state: directory
        mode: '0755'
    - name: Create the student skel directory. 
      unarchive:
        src: skel/sun-hwa-v-skel.tar
        dest: /etc/student-skel

- hosts: sun-hwa-vii.cis.cabrillo.edu
  name: 'Customize sun-hwa-vii'
  remote_user: root 
  tags: 
    - sun-hwa-vii
    - cis90
  tasks:
    - name: Setting the hostname 
      hostname: 
        name: sun-hwa-vii.cis.cabrillo.edu       
    - name: Remove motd messages.
      file:
        path: '/etc/update-motd.d/{{ item }}'
        state: absent
      loop:
        - 50-landscape-sysinfo
        - 80-esm
        - 90-updates-available
        - 95-hwe-eol
        - 98-fsck-at-reboot
        - 10-help-text
        - 50-motd-news
        - 80-livepatch
        - 91-release-upgrade
        - 97-overlayroot
        - 98-reboot-required
    - name: Copy the test bundle 
      copy: 
        src: ../../cis-90/tests/test-1-bundle/
        dest: /root
        remote_src: no 
        mode: preserve 
    - name: Run the setup script. 
      shell: 
        chdir: /root
        cmd: ./trouble-T1
