all:
  hosts:
    tux.cis.cabrillo.edu:
    jupyter.cis.cabrillo.edu:
  
  children:
    # Class specific groups.
    cis90:
      hosts:
        opus3.cis.cabrillo.edu:
        freedom.cis.cabrillo.edu:
        defiant.cis.cabrillo.edu:
        intrepid.cis.cabrillo.edu:
        enterprise.cis.cabrillo.edu:
        excalibur.cis.cabrillo.edu:
        lexington.cis.cabrillo.edu:
        sun-hwa-v.cis.cabrillo.edu:
        sun-hwa-vii.cis.cabrillo.edu:
        sun-hwa-p3.cis.cabrillo.edu:
        sun-hwa-t3.cis.cabrillo.edu:

    # Functional groups.
    jupyterhub:
      hosts:
        jupyter.cis.cabrillo.edu:
    
    # Type specific groups.
    centos:
      hosts:
        freedom.cis.cabrillo.edu:
        sun-hwa-v.cis.cabrillo.edu:
    mint:
      hosts:
        defiant.cis.cabrillo.edu:
    ubuntu:
      hosts:
        opus3.cis.cabrillo.edu:
        intrepid.cis.cabrillo.edu:
        sun-hwa-vii.cis.cabrillo.edu:
        sun-hwa-p3.cis.cabrillo.edu:
        sun-hwa-t3.cis.cabrillo.edu:
    debian:
      hosts:
        enterprise.cis.cabrillo.edu:
    fedora:
      hosts:
        excalibur.cis.cabrillo.edu:
    opensuse:
      hosts:
        lexington.cis.cabrillo.edu:
