--- 
# Setup sun-hwa-t1
- hosts: sun-hwa-t1.cis.cabrillo.edu
  name: Add cis-90 group.
  remote_user: root 
  tags: 
    - cis90
  tasks:
    - name: Add the cis90 group.
      group:
        name: cis90
        state: present

- hosts: sun-hwa-t1.cis.cabrillo.edu
  name: Install packages on Ubuntu hosts.
  remote_user: root 
  tags: 
    - cis90
  tasks:
    - name: Install base packages on Ubuntu
      apt:
        pkg:
          - tree
          - zsh
          - python3-pip
          - sysvbanner
          - emacs
          - spell 

# Add motd files. 
- hosts: sun-hwa-t1.cis.cabrillo.edu
  name: 'Customize sun-hwa-t1'
  remote_user: root 
  tags: 
    - sun-hwa-t1
    - cis90
  tasks:
    - name: Remove motd messages.
      file:
        path: '/etc/update-motd.d/{{ item }}'
        state: absent
      loop:
        - 50-landscape-sysinfo
        - 80-esm
        - 90-updates-available
        - 95-hwe-eol
        - 98-fsck-at-reboot
        - 10-help-text
        - 50-motd-news
        - 80-livepatch
        - 91-release-upgrade
        - 97-overlayroot
        - 98-reboot-required

# Add old test infrastructure
- hosts: sun-hwa-t1.cis.cabrillo.edu
  name: 'Customize sun-hwa-t1'
  remote_user: root 
  tags: 
    - sun-hwa-t1
    - cis90
  tasks:
    - name: Copy the test bundle 
      copy: 
        src: ../cis-90/tests/test-1-bundle/
        dest: /root
        remote_src: no 
        mode: preserve 
    - name: Run the setup script. 
      shell: 
        chdir: /root
        cmd: ./trouble-T1


# Add new test infrastructure
- hosts: sun-hwa-t1.cis.cabrillo.edu
  name: 'Add new test infrastructure'
  remote_user: root 
  tags: 
    - sun-hwa-t1
    - cis90
    - newtest
  tasks:
    - name: Check out the lifealgorithmic infrastructure.
      git:
        repo: 'https://github.com/mike-matera/lifealgorithmic-tools.git'
        dest: /opt/lifealgorithmic
    - name: Install the lifealgorithmic infrastructure.
      pip:
        name: file:///opt/lifealgorithmic
        extra_args: -e 
    - name: Copy the test program
      copy: 
        src: ../cis-90/tests/midterm-1-sp21/midterm-1-sp21.py
        dest: /root
        remote_src: no 
        mode: preserve 
    - name: Compile the test. 
      shell: |
        armor midterm-1-sp21.py
        cp midterm-1-sp21 /usr/local/bin
      args:
        chdir: /root

# Add users
- hosts: sun-hwa-t1.cis.cabrillo.edu
  name: 'Customize sun-hwa-t1'
  remote_user: root 
  tags: 
    - sun-hwa-t1
    - cis90
  tasks:
    - include_vars: cis-90-users.yaml
    - include_vars: setup/dogs.yaml
    - name: Add dog accounts.
      user:
        name: "{{ item.name }}"
        comment: "{{ item.comment }}"
        password: "{{ item.password }}"
        groups: "{{ item.groups }}"
        home: "{{ item.home }}"
        skeleton: /etc/student-skel
        shell: /bin/bash
        append: yes
      loop: "{{ dogs | flatten(levels=1) }}"
    - name: Add opus3 key to dog accounts.
      authorized_key:
        user: "{{ item.name }}"
        state: present
        key: "{{ lookup('file', 'roles/common/files/opus.pub') }}"
      loop: "{{ dogs | flatten(levels=1) }}"

    - name: Add user accounts.
      user:
        name: "{{ item.name }}"
        comment: "{{ item.realname }}"
        password: "{{ item.password }}"
        state: "{{ item.state }}"
        shell: /bin/bash
        groups: "users,cis90"
        home: "/home/cis90/{{ item.name }}"
        append: yes
      loop: "{{ users | flatten(levels=1) }}"
