
- name: Install the frotz player
  ansible.builtin.apt:
    name:
      - frotz 
    state: latest
    cache_valid_time: 3600
- name: Install the Zork binaries 
  ansible.builtin.unarchive:
    src: files/zork1.tar.gz
    dest: /opt
- name: Make the zork executable.
  ansible.builtin.copy:
    src: files/zork
    dest: /usr/local/bin/zork
    owner: root
    group: root
    mode: '0755'