
- name: Assign hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Add caddy repository. 
  apt_repository:
    repo: deb [trusted=yes] https://apt.fury.io/caddy/ / 
    state: present
    filename: caddy

- name: Install caddy
  apt:
    update-cache: yes
    pkg: 
      - caddy

- name: Configure caddy 
  copy:
    content: |
      {{ inventory_hostname }}

      reverse_proxy 127.0.0.1:8000
    dest: /etc/caddy/Caddyfile

- name: Reload caddy
  service:
    name: caddy
    state: reloaded

- name: Install packages. 
  apt:
    update_cache: yes
    pkg:
      - python3-pip
      - python3-venv

- name: Install newer node by snap
  snap:
    name: node
    channel: 10/stable
    classic: yes

- name: Install Python wheel. 
  pip:
    virtualenv: /opt/jupyterhub
    virtualenv_command: /usr/bin/python3 -m venv
    name:
      - wheel 

- name: Install JupyterHub.
  pip:
    virtualenv: /opt/jupyterhub
    virtualenv_command: /usr/bin/python3 -m venv
    name:
      - jupyterhub 
      - jupyterlab 
      - ipywidgets

- name: Install JS components.
  environment:
    PATH: "{{ ansible_env.PATH }}:/snap/bin"
  npm:
    name: configurable-http-proxy
    global: yes

- name: Create the JupyterHub configuration
  file:
    path: /opt/jupyterhub/etc/jupyterhub
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create default JupyterHub configuration 
  shell: /opt/jupyterhub/bin/jupyterhub --generate-config 
  args:
    chdir: /opt/jupyterhub/etc/jupyterhub
    creates: /opt/jupyterhub/etc/jupyterhub/jupyterhub_config.py        

- name: Set JupyterLab to the default interface
  lineinfile:
    path: /opt/jupyterhub/etc/jupyterhub/jupyterhub_config.py
    regexp: 'c.Spawner.default_url'
    line: c.Spawner.default_url = '/lab' 

- name: Set JupyterLab URL
  lineinfile:
    path: /opt/jupyterhub/etc/jupyterhub/jupyterhub_config.py
    regexp: 'c.JupyterHub.bind_url'
    line: c.JupyterHub.bind_url = 'http://localhost:8000/'

- name: Create the JupyterHub service 
  file:
    path: /opt/jupyterhub/etc/systemd
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Write JupyterHub serivce file. 
  blockinfile:
    path: /opt/jupyterhub/etc/systemd/jupyterhub.service
    create: yes
    block: |
      [Unit]
      Description=JupyterHub
      After=syslog.target network.target

      [Service]
      User=root
      Environment="PATH=/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/jupyterhub/bin"
      ExecStart=/opt/jupyterhub/bin/jupyterhub -f /opt/jupyterhub/etc/jupyterhub/jupyterhub_config.py

      [Install]
      WantedBy=multi-user.target

- name: Install JupyterHub service. 
  file: 
    src: /opt/jupyterhub/etc/systemd/jupyterhub.service 
    dest: /etc/systemd/system/jupyterhub.service
    owner: root
    group: root
    state: link

- name: Enable and start JupyterHub
  systemd:
    name: jupyterhub
    enabled: yes
    state: started

- name: Enable Jupyterlab Widgets 
  shell:
    cmd: |
      . /opt/jupyterhub/bin/activate 
      export PATH="/snap/bin:$PATH"
      jupyter labextension install @jupyter-widgets/jupyterlab-manager
