
- hosts: all
  name: Generate host groups by distro.
  tasks:
    - name: Classify hosts depending on their OS distribution
      group_by:
        key: os_{{ ansible_facts['distribution'] }}

- hosts: all
  become: true
  name: Install packages.
  tasks: 
    - ansible.builtin.package:
        name:
          "{{ packages }}"
        state: latest

- hosts: all 
  name: Install MOTD
  become: yes
  roles:
    - role: motd
      motdname: "{{inventory_hostname_short}}"
      dest: /usr/local/bin/scavenge 

- hosts: opus.cis.cabrillo.edu 
  name: Install Zork  
  become: true
  tags:
    - zork
  roles:
    - zork 

- hosts: opus.cis.cabrillo.edu 
  name: Install stuff for the final project. 
  become: true 
  tags:
    - depot
  tasks:
    - name: Create the depot directory 
      ansible.builtin.unarchive:
        src: files/depot.tar.xz
        dest: /home/cis90
    - name: Install allscripts
      ansible.builtin.copy:
        src: files/allscripts
        dest: /usr/local/bin/allscripts
        mode: '755'
        owner: root
        group: root 
        
- hosts: opus.cis.cabrillo.edu 
  name: Create student skeleton directory 
  become: true
  tasks:
    - name: Untar the skeleton 
      ansible.builtin.unarchive:
        src: files/cis90-skel.tar
        dest: /etc/skel

- hosts: all 
  name: Add KROZ configuration to the default bashrc.  
  become: true
  tasks:
    - name: Add KROZ watcher setup.
      ansible.builtin.blockinfile:
        path: /etc/skel/.bashrc
        append_newline: true
        prepend_newline: true
        block: |
          # Setup cis-90 application config.
          export PEX_VENV=1
          eval "$(cis90 config)"

- hosts: all
  name: Add users and groups
  tags:
    - users
  become: true
  tasks:
    - include_vars: ./users/ansible-user-data.yaml

    - name: Add the cis90 group.
      group:
        name: cis90
        state: present

    - name: Add user groups.
      group:
        gid: "{{ item.uid }}"
        name: "{{ item.name }}"
      loop: "{{ users | flatten(levels=1) }}"

    - name: Add user accounts.
      user:
        uid: "{{ item.uid }}"
        group: "{{ item.name }}"
        name: "{{ item.name }}"
        comment: "{{ item.comment }}"
        home: "/home/cis90/{{ item.name }}"
        groups: ['users', 'cis90']
        shell: /bin/bash
        append: yes
      loop: "{{ users | flatten(levels=1) }}"

    - name: Authorize the public key 
      ansible.posix.authorized_key:
        user: "{{ item.name }}"
        key: "{{ item.pub_key }}"
      loop: "{{ users | flatten(levels=1) }}"

    - name: Install SSH private key
      ansible.builtin.copy:
        content: "{{ item.priv_key }}\n"
        dest: "/home/cis90/{{ item.name }}/.ssh/id_ed25519"
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
        mode: '0600'
      loop: "{{ users | flatten(levels=1) }}"

    - name: Install SSH public key
      ansible.builtin.copy:
        content: "{{ item.pub_key }}\n"
        dest: "/home/cis90/{{ item.name }}/.ssh/id_ed25519.pub"
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
        mode: '0600'
      loop: "{{ users | flatten(levels=1) }}"

- hosts: all
  name: Install kroz player and utilities
  tags:
    - kroz
  become: true
  tasks:
    - name: "Install kroz binary"
      ansible.builtin.copy:
        src: "../dist/kroz.pex"
        dest: "/usr/bin/kroz"
        owner: "root"
        group: "root"
        mode: '0755'
    - name: "Install cis90 binary"
      ansible.builtin.copy:
        src: "../dist/cis90.pex"
        dest: "/usr/bin/cis90"
        owner: "root"
        group: "root"
        mode: '0755'
