
- hosts: all
  name: Generate host groups by distro.
  tasks:
    - name: Classify hosts depending on their OS distribution
      group_by:
        key: os_{{ ansible_facts['distribution'] }}

- hosts: os_Ubuntu 
  name: Update package cache on Ubuntu
  become: true
  tasks:
    - lineinfile:
        path: /etc/apt/apt.conf.d/proxy99.conf
        create: yes
        regexp: '^Acquire::http::Proxy'
        line: Acquire::http::Proxy "http://rack0.maas:8000/";
    - ansible.builtin.apt:
        update_cache: yes

- hosts: all
  become: true
  name: Install packages.
  tasks: 
    - ansible.builtin.package:
        name:
          "{{ packages }}"
        state: latest

- hosts: all
  become: false
  name: Install Python packages.
  tasks: 
    - ansible.builtin.pip:
        name: 
          - git+https://github.com/mike-matera/PyScramble.git
