
#
# Add users and groups to hosts 
#
- hosts: all
  name: Add users and groups
  become: true
  tags:
    - users
  tasks:
    - include_vars: users-data.yaml
    - name: Add the cis90 group.
      group:
        name: cis90
        state: present
    - name: Add user groups.
      group:
        gid: "{{ item.uid }}"
        name: "{{ item.name }}"
      loop: "{{ users | flatten(levels=1) }}"
    - name: Add user accounts.
      user:
        uid: "{{ item.uid }}"
        group: "{{ item.name }}"
        name: "{{ item.name }}"
        comment: "{{ item.comment }}"
        home: "/home/cis90/{{ item.name }}"
        groups: ['users', 'cis90']
        shell: /bin/bash
        append: yes
      loop: "{{ users | flatten(levels=1) }}"

- hosts: all
  name: Add extra users and groups
  become: true
  tags:
    - users
  tasks:
    - include_vars: extra-users-data.yaml
    - name: Add the cis90 group.
      group:
        name: cis90
        state: present
    - name: Remove extra user accounts.
      user:
        name: "{{ item.name }}"
        state: absent
        remove: yes
      loop: "{{ removes | flatten(levels=1) }}"
    - name: Remove extra user groups.
      group:
        state: absent
        name: "{{ item.name }}"
      loop: "{{ removes | flatten(levels=1) }}"

    - name: Add user groups.
      group:
        gid: "{{ item.uid }}"
        name: "{{ item.name }}"
      loop: "{{ users | flatten(levels=1) }}"
    - name: Add user accounts.
      user:
        uid: "{{ item.uid }}"
        group: "{{ item.name }}"
        name: "{{ item.name }}"
        comment: "{{ item.comment }}"
        home: "/home/cis90/{{ item.name }}"
        groups: ['users', 'cis90']
        shell: /bin/bash
        append: yes
      loop: "{{ users | flatten(levels=1) }}"

## Base packages
- hosts: all
  name: Generate host groups by distro.
  tags:
    - packages
  tasks:
    - name: Classify hosts depending on their OS distribution
      group_by:
        key: os_{{ ansible_facts['distribution'] }}

- hosts: os_Ubuntu 
  name: Update package cache on Ubuntu
  become: true
  tags:
    - packages
  tasks:
    - ansible.builtin.apt:
        update_cache: yes

- hosts: all
  become: true
  name: Install packages.
  tags:
    - packages
  tasks: 
    - ansible.builtin.package:
        name:
          "{{ packages }}"
        state: latest

- hosts: all
  become: true
  name: Install Python packages.
  tags:
    - packages
  tasks: 
    - ansible.builtin.pip:
        name: 
          - pip
    - ansible.builtin.pip:
        name: 
          - wheel
    - ansible.builtin.pip:
        name: 
          - git+https://github.com/mike-matera/PyScramble.git
          - git+https://github.com/mike-matera/cloud-linux.git#subdirectory=libs

- hosts: all
  name: Install the scavenger hunt
  become: true
  tags:
    - scavenge
  roles:
    - { role: labscript, source: ../labs/scavenge.py, dest: /usr/local/bin/scavenge }

#
# SSH Configuration 
#
- hosts: all
  become: true
  name: Setup SSH
  tags:
    - ssh
  tasks: 
    - name: Create the ca directory
      ansible.builtin.file:
        path: /etc/ssh/ca
        state: directory
        mode: '0700'
    - name: Copy the SSH CA public key
      ansible.builtin.copy:
        src: ../login-servers/secrets/ca_key.pub
        dest: /etc/ssh/ca/ca_key.pub
        owner: root
        group: root
        mode: '0644'
    - name: Copy the SSH CA private key
      ansible.builtin.copy:
        src: ../login-servers/secrets/ca_key
        dest: /etc/ssh/ca/ca_key
        owner: root
        group: root
        mode: '0600'
    - name: Sign the Host key 
      ansible.builtin.shell: ssh-keygen -s /etc/ssh/ca/ca_key -I ${HOSTNAME} -h /etc/ssh/ssh_host_rsa_key.pub
      args:
        creates: /etc/ssh/ssh_host_rsa_key-cert.pub
    - name: Make SSH use the CA key
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^TrustedUserCAKeys'
        line: TrustedUserCAKeys /etc/ssh/ca/ca_key.pub 
    # This seems to be broken on Debian/Ubuntu until after package updates????
    - name: Make SSH use the signed host key 
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^HostCertificate'
        line: HostCertificate /etc/ssh/ssh_host_rsa_key-cert.pub
    - name: Make SSH trust signed hosts
      ansible.builtin.shell: echo '@cert-authority *' $(sudo cat /etc/ssh/ca/ca_key.pub) > /etc/ssh/ssh_known_hosts
      args:
        creates: /etc/ssh/ssh_known_hosts
    - name: Restart SSH
      ansible.builtin.service:
        name: sshd
        state: restarted
