#
# Add extra users
#
- hosts: all
  name: Add extra users and groups
  become: true
  tasks:
    - include_vars: extra-users-data.yaml

    - name: Add the cis90 group.
      group:
        name: cis90
        state: present

    - name: Remove extra user accounts.
      user:
        name: "{{ item.name }}"
        state: absent
        remove: yes
      loop: "{{ removes | flatten(levels=1) }}"
    - name: Remove extra user groups.
      group:
        state: absent
        name: "{{ item.name }}"
      loop: "{{ removes | flatten(levels=1) }}"

    - name: Add user groups.
      group:
        gid: "{{ item.uid }}"
        name: "{{ item.name }}"
      loop: "{{ users | flatten(levels=1) }}"
    - name: Add user accounts.
      user:
        uid: "{{ item.uid }}"
        group: "{{ item.name }}"
        name: "{{ item.name }}"
        comment: "{{ item.comment }}"
        home: "/home/cis90/{{ item.name }}"
        groups: ['users', 'cis90']
        shell: /bin/bash
        append: yes
        password: {{  item.sid | password_hash('sha512', 'asdjf234') }}
      loop: "{{ users | flatten(levels=1) }}"
