#
# Add users and groups to hosts 
#
- hosts: all 
  name: Create student skeleton directory 
  become: true
  tasks:
    - name: Untar the skeleton 
      ansible.builtin.file:
        path: /etc/cis90-skel
        state: directory 
        mode: '755'
    - name: Untar the skeleton 
      ansible.builtin.unarchive:
        src: files/cis90-skel.tar
        dest: /etc/cis90-skel 
    - name: Copy system skel files. 
      ansible.builtin.copy:
        src: /etc/skel/ 
        dest: /etc/cis90-skel/
  
- hosts: all
  name: Add users and groups
  become: true
  tasks:
    - include_vars: users-data.yaml

    - name: Add the cis90 group.
      group:
        name: cis90
        state: present

    - name: Add user groups.
      group:
        gid: "{{ item.uid }}"
        name: "{{ item.name }}"
      loop: "{{ users | flatten(levels=1) }}"

    - name: Add user accounts.
      user:
        uid: "{{ item.uid }}"
        group: "{{ item.name }}"
        name: "{{ item.name }}"
        comment: "{{ item.comment }}"
        home: "/home/cis90/{{ item.name }}"
        groups: ['users', 'cis90']
        skeleton: /etc/cis90-skel
        shell: /bin/bash
        append: yes
        password: "{{ item.sid | password_hash('sha512') }}"
      loop: "{{ users | flatten(levels=1) }}"
