name: build-key-signer

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - src/**
      - playbooks/**
      - MANIFEST.in
      - pyproject.toml
      - README.md
      - uv.lock
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs: 
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          tags: |
            type=ref,event=branch
            type=sha
          images: ${{ env.REGISTRY }}/mike-matera/cis-90-devcontainer

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./.devcontainer/Dockerfile.devcontainer
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}